[package]
name = "http_static"
version = "0.1.0"
authors = ["arjun <arj1singh@gmail.com>"]
edition = "2018"

[dependencies]
bytes = "0.4"
futures = "0.1"
mime_guess = "2.0.0-alpha.6"
tokio = "0.1.6"
tower-web = "0.3.3"
http = "0.1"
tokio-fs = "0.1"

[profile.release]
lto = true
